version: '3.7'

services:
  postgres:
    container_name: pucrs-subscription-control-system-nest-pg
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=subscription-control-system-nest-pg
